version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-name: homeassistant
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
