name: autotag

on:
  push:
    paths:
      - requirements.txt
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: onemedical/action-general-autotag@b6b9477c3343c3c3b517372e7d29a4d62c0d38a2
      with:
        GITHUB_TOKEN: "${{ secrets.AUTOTAG }}"
        source_file: "requirements.txt"
        extraction_regex: "homeassistant==(\\d+.\\d+.\\d+)"
        tag_message: ""
