name: autotag

on:
  push:
    paths:
      - requirements.txt
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: onemedical/action-general-autotag@1.1.1
      with:
        GITHUB_TOKEN: "${{ secrets.AUTOTAG }}"
        source_file: "requirements.txt"
        extraction_regex: "homeassistant==(\\d+.\\d+.\\d+)"
        tag_message: ""
