name: autotag

on:
  pull_request:
    paths:
      - requirements.txt
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@master
    - uses: jaliborc/action-general-autotag@1.0.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        source_file: "requirements.txt"
        extraction_regex: "homeassistant==(\\d+.\\d+.\\d+)"
        tag_message: ""
